# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "cars", :force => true do |t|
    t.column "SPZ",          :string
    t.column "marque",       :string
    t.column "type",         :string
    t.column "manufactured", :date
    t.column "acquisition",  :date
    t.column "user_id",      :integer
  end

  create_table "customers", :force => true do |t|
    t.column "company",       :string
    t.column "street",        :string
    t.column "street_number", :integer
    t.column "town",          :string
    t.column "phone",         :integer
    t.column "email",         :string
    t.column "fax",           :integer
    t.column "web",           :string
    t.column "ICO",           :integer
    t.column "DIC",           :integer
    t.column "user_id",       :integer
  end

  create_table "documents", :force => true do |t|
    t.column "earning", :boolean
    t.column "issue",   :date
  end

  create_table "drivers", :force => true do |t|
    t.column "name",            :string
    t.column "surname",         :string
    t.column "personal_number", :integer
    t.column "driving_licence", :string
    t.column "phone",           :integer
    t.column "user_id",         :integer
  end

  create_table "invoices", :force => true do |t|
    t.column "Description",  :string
    t.column "IssueDate",    :date
    t.column "shipmentdate", :date
    t.column "user_id",      :integer
    t.column "customer_id",  :integer
  end

  create_table "journeys", :force => true do |t|
    t.column "car_id",            :integer
    t.column "begun",             :datetime
    t.column "finished",          :datetime
    t.column "from_where",        :string
    t.column "where",             :string
    t.column "purpose",           :text
    t.column "driver_id",         :integer
    t.column "tachymeter_before", :integer
    t.column "tachymeter_after",  :integer
    t.column "user_id",           :integer
  end

  create_table "lineitems", :force => true do |t|
    t.column "invoice_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
  end

end
